### ISSUE TITLE
[Language] Libraries with FFT on UNIX machines

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#1]
<pre> lernerb@turtles:~$ find /usr/lib -name *fft* </pre>

<pre>
/usr/lib/python2.6/dist-packages/numpy/oldnumeric/fft.pyc
/usr/lib/python2.6/dist-packages/numpy/oldnumeric/fft.py
/usr/lib/python2.6/dist-packages/numpy/numarray/fft.pyc
/usr/lib/python2.6/dist-packages/numpy/numarray/fft.py
/usr/lib/python2.6/dist-packages/numpy/fft
/usr/lib/python2.6/dist-packages/numpy/fft/tests/test_fftpack.py
/usr/lib/python2.6/dist-packages/numpy/fft/tests/test_fftpack.pyc
/usr/lib/python2.6/dist-packages/numpy/fft/fftpack_lite.so
/usr/lib/python2.6/dist-packages/numpy/fft/fftpack.pyc
/usr/lib/python2.6/dist-packages/numpy/fft/fftpack.py
/usr/lib/python2.6/dist-packages/scipy/fftpack
/usr/lib/python2.6/dist-packages/scipy/fftpack/fftpack_version.py
/usr/lib/python2.6/dist-packages/scipy/fftpack/_fftpack.so
/usr/lib/python2.6/dist-packages/scipy/fftpack/fftpack_version.pyc

/usr/lib/python2.5/site-packages/numpy/oldnumeric/fft.pyc
/usr/lib/python2.5/site-packages/numpy/oldnumeric/fft.py
/usr/lib/python2.5/site-packages/numpy/numarray/fft.pyc
/usr/lib/python2.5/site-packages/numpy/numarray/fft.py
/usr/lib/python2.5/site-packages/numpy/fft
/usr/lib/python2.5/site-packages/numpy/fft/tests/test_fftpack.py
/usr/lib/python2.5/site-packages/numpy/fft/tests/test_fftpack.pyc
/usr/lib/python2.5/site-packages/numpy/fft/fftpack_lite.so
/usr/lib/python2.5/site-packages/numpy/fft/fftpack.pyc
/usr/lib/python2.5/site-packages/numpy/fft/fftpack.py
/usr/lib/python2.5/site-packages/scipy/fftpack
/usr/lib/python2.5/site-packages/scipy/fftpack/fftpack_version.py
/usr/lib/python2.5/site-packages/scipy/fftpack/_fftpack.so
/usr/lib/python2.5/site-packages/scipy/fftpack/fftpack_version.pyc

/usr/lib/libfftw3_threads.so.3.2.3
/usr/lib/libfftw3l.so.3
/usr/lib/libfftw3f_threads.so.3
/usr/lib/libfftw3f.so.3
/usr/lib/libfftw3l_threads.so.3
/usr/lib/libfftw3f_threads.so.3.2.3
/usr/lib/libgstfft-0.10.so.0
/usr/lib/libgstfft-0.10.so.0.18.0
/usr/lib/libfftw3f.so.3.2.3

/usr/lib/libfftw3l.o.3.2.3
/usr/lib/libfftw3l_threads.so.3.2.3
/usr/lib/libfftw3_threads.so.3
/usr/lib/libfftw3.so.3
/usr/lib/libfftw3.so.3.2.3

/usr/lib/octave/3.2.2/oct/i486-pc-linux-gnu/fft.oct
/usr/lib/octave/3.2.2/oct/i486-pc-linux-gnu/fftn.oct
/usr/lib/octave/3.2.2/oct/i486-pc-linux-gnu/fft2.oct
/usr/lib/octave/3.2.2/oct/i486-pc-linux-gnu/fftw.oct

/usr/lib/R/library/stats/help/fft
/usr/lib/R/library/stats/R-ex/fft.R
</pre>

**Comment by nsheaps** [comment]
Looks like python it is?

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
99% we're going to use that, I'm looking at examples and people seem to be doing basic image matching in like 6 lines @ http://stackoverflow.com/questions/1819124/image-comparison-algorithm

**Comment by nsheaps** [comment]
http://stackoverflow.com/posts/1819195/revisions is an example of using
numpy in 09 which is installed in 2.5 and 2.6 on the ccis machines

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
And it looks like this is _exactly_ what we need to do, and we have the libraries : http://stackoverflow.com/questions/7670112/finding-a-subimage-inside-a-numpy-image
