### ISSUE TITLE
Our change to the threshold has MORE tests failing now

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#11]
run during class...

Testing assignment4:
[PASS] Test: "./spims abc def"  
       Output: Error: Invalid Arguments. Must provide a pattern(-p) and source(-s) image!

[PASS] Test: "./spims -p abc"  
       Output: Error: Invalid Arguments. Must provide a pattern(-p) and source(-s) image!

[PASS] Test: "./spims -s def"  
       Output: Error: Invalid Arguments. Must provide a pattern(-p) and source(-s) image!

[PASS] Test: "./spims -p abc -s def"  
       Output: Error: Image files cannot be found!

[PASS] Test: "./spims -p /course/cs4500wc/Assignments/A4/Patterns/nature.jpg -s ./bitmap.bmp"
       Output: Error: Provided images must be GIF, JPEG, or PNG!

[PASS] Test: "./spims -p /course/cs4500wc/Assignments/A4/Patterns/black.jpg -s /course/cs4500wc/Assignments/A4/Sources/bb0001.jpg"
       Output: black.jpg matches bb0001.jpg at 35x44+797+609

[PASS] Test: "./spims -p /course/cs4500wc/Assignments/A4/Patterns/black.jpg -s /course/cs4500wc/Assignments/A4/Sources/hh0021.jpg"
       Output: 

[PASS] Test: "./spims -p /course/cs4500wc/Assignments/A4/Patterns/cliff.png -s /course/cs4500wc/Assignments/A4/Sources/an0300.jpg"
       Output: cliff.png matches an0300.jpg at 212x146+1060+247

[FAIL] Test: "./spims -p /course/cs4500wc/Assignments/A4/Patterns/flower.gif -s /course/cs4500wc/Assignments/A4/Sources/ac1000.jpg"
       Expected output: flower.gif matches ac1000.jpg at 194x135+101+998
       Actual output  : 

[FAIL] Test: "./spims -p /course/cs4500wc/Assignments/A4/Patterns/nature.jpg -s /course/cs4500wc/Assignments/A4/Sources/hh0021.jpg"
       Expected output: nature.jpg mtches hh0021.jpg at 160x97+742+181
       Actual output  : nature.jpg matches hh0021.jpg at 160x97+742+181

[PASS] Test: "./spims -p /course/cs4500wc/Assignments/A4/Patterns/rock.jpg -s /course/cs4500wc/Assignments/A4/Sources/ar0800.jpg"
       Output: rock.jpg matches ar0800.jpg at 103x99+973+230

[    ] Test: "./spims -p /course/cs4500wc/Assignments/A4/Patterns/tree.jpg -s /course/cs4500wc/Assignments/A4/Sources/aa0010.jpg"

**Comment by LTAcosta** [comment]
That's actually only 1 failure. There is a typo in the expected result of the nature one.

**Comment by LTAcosta** [comment]
I reran all of them, and the only failure is that flower one. I'll try lowering it to like 5% and running it again

**Comment by lernerb** [comment]
Go for it.

On Fri, Feb 15, 2013 at 10:03 PM, Lennon Acosta notifications@github.comwrote:

> I reran all of them, and the only failure is that flower one. I'll try
> lowering it to like 5% and running it again
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/11#issuecomment-13639636.

## 

Brandon Lerner

**Comment by LTAcosta** [comment]
Put it down to 3%. Everything is passing. We should really try to understand what it is doing though...

**Comment by lernerb** [comment]
Along those lines, we should add failing test cases to make sure that we
are all set. That too.

On Sat, Feb 16, 2013 at 10:26 AM, Lennon Acosta notifications@github.comwrote:

> Put it down to 3%. Everything is passing. We should really try to
> understand what it is doing though...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/11#issuecomment-13652525.

## 

Brandon Lerner
