### ISSUE TITLE
All set for A4?

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#12]
If so, we need to do this:

To submit your assignment 4:
1. Put all the software you wish to submit into a single directory. Don't forget the README file. Don't put any extraneous stuff in the directory.
2. Created a gzipped tar file of that directory. Suppose, for example, that the directory you want to submit is named mydir. The recommended way to create the gzipped tar file is to cd to the directory that contains mydir, and to execute the following Linux command:
   
   tar -czf mydir.tgz mydir
   That will create a file named mydir.tgz.
3. On a CCIS Linux machine, cd to the directory that contains the gzipped tar file you created in step 2. Then type the following command, after substituting your own email address for <name>:
   
   /course/cs4500wc/submit <name> 4 mydir.tgz
4. If all goes well, step 3 will end by giving you a confirmation number. Please record your confirmation number so you can prove you have submitted the assignment.

Not bad at all, anyone have any last changes?

**Comment by nsheaps** [comment]
Did anyone submit it yet?

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
Not yet

**Comment by nsheaps** [comment]
are you going to, Brandon?

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
Yeah I'll do it. Can you run the tester with the current develop that I'll submit.

**Comment by lernerb** [comment]
https://piazza.com/class#spring2013/cs4500/10

So it looks like everyone is having problem submitting....TBA.

**Comment by lernerb** [comment]
lernerb@turtles:~$ /course/cs4500wc/submit lernerbrandon@gmail.com 4
software_dev_a4.tgz
Your assignment has been submitted successfully.
Your confirmation number is ab6c4fe6
lernerb@turtles:~$

all done

On Sun, Feb 17, 2013 at 8:32 PM, Brandon Lerner lernerbrandon@gmail.comwrote:

> Yeah I'll do it. Can you run the tester with the current develop that I'll
> submit.
> 
> Sent from my iPhone
> 
> On Feb 17, 2013, at 8:18 PM, Nathan Heaps notifications@github.com
> wrote:
> 
> are you going to, Brandon?
> 
> Sincerely,
> 
> Nathan Heaps
> Dual CS/IS | Northeastern University | CCIS Class of 2014
> ResNet Computer Technician and System Administrator | (914) 907 - 7374
> 
> On Sun, Feb 17, 2013 at 8:15 PM, Brandon Lerner notifications@github.comwrote:
> 
> > Not yet
> > 
> > Sent from my iPhone
> > 
> > On Feb 17, 2013, at 8:14 PM, Nathan Heaps notifications@github.com
> > wrote:
> > 
> > > Did anyone submit it yet?
> > > 
> > > Sincerely,
> > > 
> > > Nathan Heaps
> > > Dual CS/IS | Northeastern University | CCIS Class of 2014
> > > ResNet Computer Technician and System Administrator | (914) 907 - 7374
> > > 
> > > On Sun, Feb 17, 2013 at 1:58 PM, Brandon Lerner <
> > > notifications@github.com>wrote:
> > > 
> > > > If so, we need to do this:
> > > > 
> > > > To submit your assignment 4:
> > > > 
> > > > 1.
> > > > 
> > > > Put all the software you wish to submit into a single directory.
> > > > Don't
> > > > forget the README file. Don't put any extraneous stuff in the
> > > > directory.
> > > > 2.
> > > > 
> > > > Created a gzipped tar file of that directory. Suppose, for example,
> > > > that the directory you want to submit is named mydir. The
> > > > recommended
> > > > way
> > > > to create the gzipped tar file is to cd to the directory that
> > > > contains
> > > > mydir, and to execute the following Linux command:
> > > > 
> > > > tar -czf mydir.tgz mydir
> > > > That will create a file named mydir.tgz.
> > > > 3.
> > > > 
> > > > On a CCIS Linux machine, cd to the directory that contains the
> > > > gzipped
> > > > tar file you created in step 2. Then type the following command,
> > > > after
> > > > substituting your own email address for :
> > > > 
> > > > /course/cs4500wc/submit 4 mydir.tgz
> > > > 4.
> > > > 
> > > > If all goes well, step 3 will end by giving you a confirmation
> > > > number.
> > > > Please record your confirmation number so you can prove you have
> > > > submitted
> > > > the assignment.
> > > > 
> > > > Not bad at all, anyone have any last changes?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/lernerb/SoftwareDev/issues/12>.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/12#issuecomment-13702746>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/12#issuecomment-13702811.

## 

Brandon Lerner

**Comment by nsheaps** [comment]
I had also run it...I think we're only supposed to submit it once. Did you
not see my message on piazza that it works now?

My confirmation number was ab557c05

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
No I didn't see it. We can tell clinger we double submitted on tues
