### ISSUE TITLE
We're down to (~1 second a test, but we get the wrong answer)

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#13]
bl_hw5 branch, feel free to branch off that. If anyone wants to fool around we need to use 

signal.fftconvolve(numpySource, np.fliplr(np.flipud(numpyPattern)), 'full')

I'll do a small writeup for you guys to explain how this shit works.

**Comment by lernerb** [comment]
Okay I've pretty much figured out the code we need to run 
- https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/_template.pyx

and an example of it being run can be found here
- https://github.com/scikit-image/scikit-image/blob/master/skimage/feature/template.py

Can someone do a sanity check and download the skimage package locally, and run this match_template function.

**Comment by lernerb** [comment]
http://scikit-image.org/docs/0.7.0/auto_examples/plot_template.html

**Comment by shuuri** [comment]
Is Cython in lab machines ?

**Comment by lernerb** [comment]
No, but it's mostly used for just typing. All valid cython code is valid
python code (or something like that).

On Tue, Feb 26, 2013 at 3:57 PM, shuuri notifications@github.com wrote:

> Is Cython in lab machines ?
> 
> On Tue, Feb 26, 2013 at 3:51 PM, Brandon Lerner notifications@github.comwrote:
> 
> > http://scikit-image.org/docs/0.7.0/auto_examples/plot_template.html
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/13#issuecomment-14138910>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/13#issuecomment-14139205
> .

## 

Brandon Lerner

**Comment by shuuri** [comment]
Hey Lennon can you include your multi-input code as soon as possible in the
bl_hw5 branch and proceed from there. It currently runs under 10 min for
all the tests and all we have left after your part is the confidence level
processing

**Comment by lernerb** [comment]
(just merge what you have in a pull request to it, hopefully you didn't
touch the match template function and no conflicts exists.

On Tue, Feb 26, 2013 at 5:28 PM, shuuri notifications@github.com wrote:

> Hey Lennon can you include your multi-input code as soon as possible in
> the
> bl_hw5 branch and proceed from there. It currently runs under 10 min for
> all the tests and all we have left after your part is the confidence level
> processing
> On Feb 26, 2013 4:04 PM, "Brandon Lerner" notifications@github.com
> wrote:
> 
> > No, but it's mostly used for just typing. All valid cython code is valid
> > python code (or something like that).
> > 
> > On Tue, Feb 26, 2013 at 3:57 PM, shuuri notifications@github.com
> > wrote:
> > 
> > > Is Cython in lab machines ?
> > > 
> > > On Tue, Feb 26, 2013 at 3:51 PM, Brandon Lerner <
> > > notifications@github.com>wrote:
> > > 
> > > > http://scikit-image.org/docs/0.7.0/auto_examples/plot_template.html
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/lernerb/SoftwareDev/issues/13#issuecomment-14138910>
> > > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/lernerb/SoftwareDev/issues/13#issuecomment-14139205>
> > > .
> > 
> > ## 
> > 
> > Brandon Lerner
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/13#issuecomment-14139586>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/13#issuecomment-14143996
> .

## 

Brandon Lerner
