### ISSUE TITLE
Lets Meet tonight?

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#14]
Anyone around, past 6-7?

**Comment by nsheaps** [comment]
I'm busy :-/

**Comment by lernerb** [comment]
Tomorrow after class?

On Mon, Feb 25, 2013 at 10:34 AM, Nathan Heaps notifications@github.comwrote:

> I'm busy :-/
> On Feb 25, 2013 9:56 AM, "Brandon Lerner" notifications@github.com
> wrote:
> 
> > Anyone around, past 6-7?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/14>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/14#issuecomment-14048719.

## 

Brandon Lerner

**Comment by nsheaps** [comment]
Ok

**Comment by shuuri** [comment]
ok

**Comment by LTAcosta** [comment]
Not sure if I can meet anymore, but I'm working the added parameters, and handling multiple files

**Comment by lernerb** [comment]
Thats fine. If you need any help with the logic hit me up. I'm still
looking into the normalized cross correlation shit.

On Tue, Feb 26, 2013 at 3:02 PM, Lennon Acosta notifications@github.comwrote:

> Not sure if I can meet anymore, but I'm working the added parameters, and
> handling multiple files
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/14#issuecomment-14136406
> .

## 

Brandon Lerner
