### ISSUE TITLE
Meet tomorrow, 7pm in the lab

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#15]
Everyone free? It's due Friday @ 12pm and I'm leaving in the morning.

**Comment by LTAcosta** [comment]
Works for me

**Comment by nsheaps** [comment]
I'll probably be a touch late as I'm going to a b-day dinner with a close
friend. We're planning on being finished at 7 though, so I would imagine
730 at the latest. Is there anything I can do in the mean time?

**Comment by lernerb** [comment]
Jerk it.

On Thu, Feb 28, 2013 at 3:52 PM, Nathan Heaps notifications@github.comwrote:

> I'll probably be a touch late as I'm going to a b-day dinner with a close
> friend. We're planning on being finished at 7 though, so I would imagine
> 730 at the latest. Is there anything I can do in the mean time?
> 
> On Thu, Feb 28, 2013 at 2:09 AM, Lennon Acosta notifications@github.comwrote:
> 
> > Works for me
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/15#issuecomment-14220069>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/15#issuecomment-14256888
> .

## 

Brandon Lerner

**Comment by lernerb** [comment]
Tell suzie i say hi

On Thu, Feb 28, 2013 at 3:53 PM, Brandon Lerner lernerbrandon@gmail.comwrote:

> Jerk it.
> 
> On Thu, Feb 28, 2013 at 3:52 PM, Nathan Heaps notifications@github.comwrote:
> 
> > I'll probably be a touch late as I'm going to a b-day dinner with a close
> > friend. We're planning on being finished at 7 though, so I would imagine
> > 730 at the latest. Is there anything I can do in the mean time?
> > 
> > On Thu, Feb 28, 2013 at 2:09 AM, Lennon Acosta notifications@github.comwrote:
> > 
> > > Works for me
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/lernerb/SoftwareDev/issues/15#issuecomment-14220069>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/15#issuecomment-14256888
> > .
> 
> ## 
> 
> Brandon Lerner

## 

Brandon Lerner

**Comment by nsheaps** [comment]
Ok. To what?

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by LTAcosta** [comment]
So what is left to do for hw5?
- Multiple matches between the same two images
- Implement some kind of threshold to prevent printing when there are no matches
- Update the tester
- Some cleanup

Is there anything else?

**Comment by lernerb** [comment]
Yup that's it!

**Comment by nsheaps** [comment]
In the grading thing, he mentioned the tester. If we're not supposed to
include it then is it even worth it to update it if we know the multiple
matches uses the same code?

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
Nah we can manually test multiple matches. We just need to fix the failing tests and not include that in the zip

**Comment by lernerb** [comment]
What is left to do for hw5?
- Multiple matches between the same two images
- Implement some kind of threshold to prevent printing when there are no matches
- Update the tester [FIXED in my PR]
- Some cleanup
