### ISSUE TITLE
Assignment #6

### ISSUE THREAD

**Issue by shuuri** [lernerb/SoftwareDev#20]
CS 4500 Assignment #6
Assigned: Friday, 1 March 2013
Due: Friday, 15 March and Tuesday, 19 March 2013

Each team will present to the entire class a high-level
review of the software architecture, algorithms, and
critical data structures it is using for its semester
project software.  This high-level review should take
no more than 20 minutes, not counting questions.

Every member of every team should participate in these
reviews.

The reviews will begin on 15 March and continue on 19
and 22 March.  The order in which teams present their
reviews will be determined randomly.

**Comment by lernerb** [comment]
Everyone start reading bout fft and normalized cross correlations!

**Comment by nsheaps** [comment]
We're meeting tonight, right? what time?

**Comment by lernerb** [comment]
I'm super busy tonight with meetings. Everyone go look up the code base. We can meet at 6pm for an hour tomorrow If that works

**Comment by nsheaps** [comment]
Basic breakdown of current operation. Not high level, not final product. THIS IS NOT WHAT WE'RE PRESENTING

```
parse the args
for each pattern image path
  for each source image path
    load source image, convert to greyscale, convert to numpy array
    load pattern image, convert to greyscale, convert to numpy array
    if both images are smaller than 10px (height or width), do a brute force comparison
    else normalize arrays using FFT's (normalized cross correlation)
    print matches higher than threshold
```

**Comment by lernerb** [comment]
6pm today okay for everyone after our classes?! We should meet briefly for 30 minutes to review what we will talk about.

**Comment by shuuri** [comment]
ok where at?

**Comment by lernerb** [comment]
Hmm. How about the lab, and from there we can either go in a corner or go
upstairs.

I guess I'll go to compsoc today :P

On Thu, Mar 14, 2013 at 11:00 AM, shuuri notifications@github.com wrote:

> ok where at?
> 
> On Thu, Mar 14, 2013 at 10:53 AM, Brandon Lerner
> notifications@github.comwrote:
> 
> > 6pm today okay for everyone after our classes?! We should meet briefly
> > for
> > 30 minutes to review what we will talk about.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/20#issuecomment-14906528>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/20#issuecomment-14906965
> .

## 

Brandon Lerner

**Comment by nsheaps** [comment]
6pm is good for me.

**Comment by nsheaps** [comment]
Going to get coffee before I head there.  If you want me to get you something, text it to 914 907 7374 with name and order. You have 15 minutes to get me your order

**Comment by nsheaps** [comment]
Beasted.
