### ISSUE TITLE
SIFT fruitful research

### ISSUE THREAD

**Issue by shuuri** [lernerb/SoftwareDev#21]
Good Overview of SIFT - has an OpenCV example
http://www.aishack.in/2010/05/sift-scale-invariant-feature-transform/

Book on Computer Vision has SIFT on page 36
http://bit.ly/Zj3U54

A small example
http://www.janeriksolem.net/2009/02/sift-python-implementation.html

SIFT implementation OpenCV 
http://stackoverflow.com/questions/5461148/sift-implementation-with-opencv-2-2

**Comment by nsheaps** [comment]
3rd link (janeriksolem) has python implementation using pylab that is part of scipy

**Comment by lernerb** [comment]
We should try and find some source code of either SURF/SIFT, or even just 'template matching with scale' by this weekend. We're going to need all of next week to code

**Comment by lernerb** [comment]
https://math.ucsd.edu/programs/undergraduate/1012_honors_presentations/Natalie_Sauerwald_Thesis.pdf is pretty interesting. Also, we _might_ already deal with scaling soooo we shall see.

**Comment by lernerb** [comment]
okay we need to meet after tuesdays class. we have a lot of shit to do.

**Comment by nsheaps** [comment]
I can't meet on Tuesday, religious obligation (passover seder)

**Comment by lernerb** [comment]
'touche. All of us less jewish jews and others will meet Tuesday, and will
meet again Wednesday.

On Mon, Mar 25, 2013 at 11:02 AM, Nathan Heaps notifications@github.comwrote:

> I can't meet on Tuesday, religious obligation (passover seder)
> On Mar 25, 2013 11:01 AM, "Brandon Lerner" notifications@github.com
> wrote:
> 
> > okay we need to meet after tuesdays class. we have a lot of shit to do.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/21#issuecomment-15398170>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/21#issuecomment-15398243
> .

## 

Brandon Lerner

**Comment by nsheaps** [comment]
And on Thursday -.-

**Comment by shuuri** [comment]
So when are we meeting...

**Comment by lernerb** [comment]
right after class the 3 of us can meet tuesday. (exam)

On Mon, Mar 25, 2013 at 11:33 AM, shuuri notifications@github.com wrote:

> So when are we meeting...
> 
> On Mon, Mar 25, 2013 at 11:06 AM, Nathan Heaps notifications@github.comwrote:
> 
> > And on Thursday -.-
> > On Mar 25, 2013 11:04 AM, "Brandon Lerner" notifications@github.com
> > wrote:
> > 
> > > 'touche. All of us less jewish jews and others will meet Tuesday, and
> > > will
> > > meet again Wednesday.
> > > 
> > > On Mon, Mar 25, 2013 at 11:02 AM, Nathan Heaps <
> > > notifications@github.com>wrote:
> > > 
> > > > I can't meet on Tuesday, religious obligation (passover seder)
> > > > On Mar 25, 2013 11:01 AM, "Brandon Lerner" notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > okay we need to meet after tuesdays class. we have a lot of shit
> > > > > to
> > > > > do.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > 
> > > > https://github.com/lernerb/SoftwareDev/issues/21#issuecomment-15398170>
> > > > 
> > > > > .
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/lernerb/SoftwareDev/issues/21#issuecomment-15398243>
> > > > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Brandon Lerner
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/lernerb/SoftwareDev/issues/21#issuecomment-15398367>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/21#issuecomment-15398506>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/21#issuecomment-15400283
> .

## 

Brandon Lerner

**Comment by shuuri** [comment]
What's the exam on ?

**Comment by shuuri** [comment]
Like how many questions and etc

**Comment by nsheaps** [comment]
Fuck if we know...

**Comment by nsheaps** [comment]
I think he said mostly multiple choice and a few short answers, ~50
questions

**Comment by shuuri** [comment]
.... fuck man... how is the exam worth again ?

**Comment by lernerb** [comment]
25%?

**Comment by lernerb** [comment]
Today 8pm in 212.
