### ISSUE TITLE
Sift/Surf further research

### ISSUE THREAD

**Issue by shuuri** [lernerb/SoftwareDev#22]
http://www.cs264.org/2009/projects/web/Preshman_Mike/preshman/index.html

http://www.aishack.in/2010/05/sift-scale-invariant-feature-transform/3/

http://lu-vision-dock.blogspot.com/2009/04/sift-python-implementation.html

http://programmingcomputervision.com/downloads/Draft_20120318.pdf

http://books.google.com/books?id=9_AXCmGDiz8C&pg=PA148&lpg=PA148&dq=sift+algorithm+python+implementation&source=bl&ots=zj4XHHSzDd&sig=i9LUzAAIgY3cU9z_sNdLdh2XvP4&hl=en&sa=X&ei=eDFTUfuKC5XH4AOE0oCoCQ&ved=0CGsQ6AEwCDgK#v=onepage&q=sift%20algorithm%20python%20implementation&f=false

https://github.com/vishwa91/pyimreg/blob/master/sift.py

http://www.janeriksolem.net/2011/06/another-python-interface-for-sift.html

http://bytes.com/topic/python/answers/780670-image-matching-algorithms

http://stackoverflow.com/questions/2603713/comparing-similar-images-with-python-pil

http://stackoverflow.com/questions/15185764/deformed-template-image-matching

http://grokbase.com/t/python/python-list/083axcd13b/image-matching-algorithms

http://codereview.stackexchange.com/questions/19312/how-can-i-improve-my-image-comparison-algorithm

**Comment by nsheaps** [comment]
We should have the libraries to do any of the following:

Corner detection using Harris
http://stackoverflow.com/questions/1603688/python-image-recognition

Corner detection using FAST (part of OpenCV now, source avail in python)
http://www.edwardrosten.com/work/fast.html

Simple brute force
http://forrst.com/posts/Match_two_images_regardless_of_size_or_filters_w-wDm

Another brute force
http://notes.sovechkin.com/python_template_matching.html

Here's an idea: Find corners in both images, then take top, left most
corner found in pattern and start searching through source image for a
corner. Then find the closest one that matches and use the distance to
account for scale while looking for the others. It needs to find XX% of the
corners in order to match

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
sift source code:

http://www.janeriksolem.net/2009/02/sift-python-implementation.html

On Wed, Mar 27, 2013 at 6:44 PM, Nathan Heaps notifications@github.comwrote:

> We should have the libraries to do any of the following:
> 
> Corner detection using Harris
> http://stackoverflow.com/questions/1603688/python-image-recognition
> 
> Corner detection using FAST (part of OpenCV now, source avail in python)
> http://www.edwardrosten.com/work/fast.html
> 
> Simple brute force
> 
> http://forrst.com/posts/Match_two_images_regardless_of_size_or_filters_w-wDm
> 
> Another brute force
> http://notes.sovechkin.com/python_template_matching.html
> 
> Here's an idea: Find corners in both images, then take top, left most
> corner found in pattern and start searching through source image for a
> corner. Then find the closest one that matches and use the distance to
> account for scale while looking for the others. It needs to find XX% of
> the
> corners in order to match
> 
> Sincerely,
> 
> Nathan Heaps
> Dual CS/IS | Northeastern University | CCIS Class of 2014
> ResNet Computer Technician and System Administrator | (914) 907 - 7374
> 
> On Wed, Mar 27, 2013 at 6:02 PM, shuuri notifications@github.com wrote:
> 
> > http://www.cs264.org/2009/projects/web/Preshman_Mike/preshman/index.html
> > 
> > http://www.aishack.in/2010/05/sift-scale-invariant-feature-transform/3/
> > 
> > http://lu-vision-dock.blogspot.com/2009/04/sift-python-implementation.html
> > 
> > http://programmingcomputervision.com/downloads/Draft_20120318.pdf
> > 
> > http://books.google.com/books?id=9_AXCmGDiz8C&pg=PA148&lpg=PA148&dq=sift+algorithm+python+implementation&source=bl&ots=zj4XHHSzDd&sig=i9LUzAAIgY3cU9z_sNdLdh2XvP4&hl=en&sa=X&ei=eDFTUfuKC5XH4AOE0oCoCQ&ved=0CGsQ6AEwCDgK#v=onepage&q=sift%20algorithm%20python%20implementation&f=false
> > 
> > https://github.com/vishwa91/pyimreg/blob/master/sift.py
> > 
> > http://www.janeriksolem.net/2011/06/another-python-interface-for-sift.html
> > 
> > http://bytes.com/topic/python/answers/780670-image-matching-algorithms
> > 
> > http://stackoverflow.com/questions/2603713/comparing-similar-images-with-python-pil
> > 
> > http://stackoverflow.com/questions/15185764/deformed-template-image-matching
> > 
> > http://grokbase.com/t/python/python-list/083axcd13b/image-matching-algorithms
> > 
> > http://codereview.stackexchange.com/questions/19312/how-can-i-improve-my-image-comparison-algorithm
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/22>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/22#issuecomment-15557942
> .

## 

Brandon Lerner

**Comment by nsheaps** [comment]
Using the link that Brandon just posted means that we'll be venturing into
C as well.

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
i'll be in 212 in about 15 minutes. see you guys there (or early if you
come)

On Wed, Mar 27, 2013 at 7:02 PM, Nathan Heaps notifications@github.comwrote:

> Using the link that Brandon just posted means that we'll be venturing into
> C as well.
> 
> Sincerely,
> 
> Nathan Heaps
> Dual CS/IS | Northeastern University | CCIS Class of 2014
> ResNet Computer Technician and System Administrator | (914) 907 - 7374
> 
> On Wed, Mar 27, 2013 at 6:59 PM, Brandon Lerner notifications@github.comwrote:
> 
> > sift source code:
> > 
> > http://www.janeriksolem.net/2009/02/sift-python-implementation.html
> > 
> > On Wed, Mar 27, 2013 at 6:44 PM, Nathan Heaps notifications@github.comwrote:
> > 
> > > We should have the libraries to do any of the following:
> > > 
> > > Corner detection using Harris
> > > http://stackoverflow.com/questions/1603688/python-image-recognition
> > > 
> > > Corner detection using FAST (part of OpenCV now, source avail in
> > > python)
> > > http://www.edwardrosten.com/work/fast.html
> > > 
> > > Simple brute force
> > 
> > http://forrst.com/posts/Match_two_images_regardless_of_size_or_filters_w-wDm
> > 
> > > Another brute force
> > > http://notes.sovechkin.com/python_template_matching.html
> > > 
> > > Here's an idea: Find corners in both images, then take top, left most
> > > corner found in pattern and start searching through source image for a
> > > corner. Then find the closest one that matches and use the distance to
> > > account for scale while looking for the others. It needs to find XX%
> > > of
> > > the
> > > corners in order to match
> > > 
> > > Sincerely,
> > > 
> > > Nathan Heaps
> > > Dual CS/IS | Northeastern University | CCIS Class of 2014
> > > ResNet Computer Technician and System Administrator | (914) 907 - 7374
> > > 
> > > On Wed, Mar 27, 2013 at 6:02 PM, shuuri notifications@github.com
> > > wrote:
> > > 
> > > > http://www.cs264.org/2009/projects/web/Preshman_Mike/preshman/index.html
> > > > 
> > > > http://www.aishack.in/2010/05/sift-scale-invariant-feature-transform/3/
> > 
> > http://lu-vision-dock.blogspot.com/2009/04/sift-python-implementation.html
> > 
> > > > http://programmingcomputervision.com/downloads/Draft_20120318.pdf
> > 
> > http://books.google.com/books?id=9_AXCmGDiz8C&pg=PA148&lpg=PA148&dq=sift+algorithm+python+implementation&source=bl&ots=zj4XHHSzDd&sig=i9LUzAAIgY3cU9z_sNdLdh2XvP4&hl=en&sa=X&ei=eDFTUfuKC5XH4AOE0oCoCQ&ved=0CGsQ6AEwCDgK#v=onepage&q=sift%20algorithm%20python%20implementation&f=false
> > 
> > > > https://github.com/vishwa91/pyimreg/blob/master/sift.py
> > 
> > http://www.janeriksolem.net/2011/06/another-python-interface-for-sift.html
> > 
> > > > http://bytes.com/topic/python/answers/780670-image-matching-algorithms
> > 
> > http://stackoverflow.com/questions/2603713/comparing-similar-images-with-python-pil
> > 
> > 
> > http://stackoverflow.com/questions/15185764/deformed-template-image-matching
> > 
> > 
> > http://grokbase.com/t/python/python-list/083axcd13b/image-matching-algorithms
> > 
> > 
> > http://codereview.stackexchange.com/questions/19312/how-can-i-improve-my-image-comparison-algorithm
> > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/lernerb/SoftwareDev/issues/22>
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/lernerb/SoftwareDev/issues/22#issuecomment-15557942>
> > > .
> > 
> > ## 
> > 
> > Brandon Lerner
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/22#issuecomment-15558535>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/22#issuecomment-15558667
> .

## 

Brandon Lerner

**Comment by nsheaps** [comment]
Making a wally's run. Anyone want anything?

**Comment by shuuri** [comment]
http://www.scholarpedia.org/article/SIFT
