### ISSUE TITLE
Tasks for Assignment 7

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#23]
Points where we got off for the last one:

The software is too slow to execute some cases.                              XXX (fuck you clinger)
Multiple matches were not reported by the software.                          X    (big images don't report multiple matches)

1) Find multiple matches in FFT Image
2) Don't spit out overlap in FFT

**Comment by nsheaps** [comment]
The upstairs labs are currently locked. I'm in 102 if anyone wants to join in

**Comment by nsheaps** [comment]
Also, assignment 8 (code review) and assignment 9 (final project) have been posted. Final project due the 16th

**Comment by nsheaps** [comment]
We have moved to 212

**Comment by lernerb** [comment]
turtles:~ lernerb$ /course/cs4500wc/submit 7 sda7.tgz
Your assignment has been submitted successfully.
Your confirmation number is b4ca1b2e

**Comment by lernerb** [comment]
http://media.tumblr.com/8da34705b56e2d1508bb53235a65cb15/tumblr_inline_mke1opPKlL1qz4rgp.gif
- nathan
