### ISSUE TITLE
Assignment 8

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#33]
Everyone okay with meeting @ ~6pm this Wednesday/Thursday? There is currently a slight chance we present on Friday (and if not we will be the next Tuesday). We can take pretty much the same old presentation and change a few things, it shouldn't take that long.

(me and nathan have another presentaiton on friday, so we don't have all night)
- Brandon

**Comment by shuuri** [comment]
ok

**Comment by nsheaps** [comment]
I have a meeting at 730-9 on wednesday can we do thursday?

(brandon can do his shit without me since I'm working on it on my own time)

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by LTAcosta** [comment]
Either day works for me

**Comment by shuuri** [comment]
Same here

**Comment by lernerb** [comment]
thursday it is

On Tue, Apr 2, 2013 at 1:36 PM, shuuri notifications@github.com wrote:

> Same here
> 
> On Tue, Apr 2, 2013 at 1:30 PM, Lennon Acosta notifications@github.comwrote:
> 
> > Either day works for me
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/33#issuecomment-15790042>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/33#issuecomment-15790358
> .

## 

Brandon Lerner

**Comment by LTAcosta** [comment]
So what time exactly tonight? 6 or 6:30?

**Comment by lernerb** [comment]
6:30 in the lab. Lets go 212. Getting food now

**Comment by nsheaps** [comment]
We need to meet tomorrow and discuss scaling and if we're putting it in to the code reveiw

**Comment by lernerb** [comment]
I've discussed with two other groups doing python and talking tomorrow and
none of them have scaling. I also can't meet until after 10pm tomorrow (but
i have an exam i would like to study for)

On Sun, Apr 7, 2013 at 8:01 PM, Nathan Heaps notifications@github.comwrote:

> We need to meet tomorrow and discuss scaling and if we're putting it in to
> the code reveiw
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/33#issuecomment-16027321
> .

## 

Brandon Lerner
