### ISSUE TITLE
Stuff to do from now until submission

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#36]
1) 1 by 1 source case testing

2) Why is airplane not working???

3) Multithread printing

4) speed er up?

**Comment by shuuri** [comment]
Are you guys still there?

**Comment by lernerb** [comment]
No

**Comment by shuuri** [comment]
K. When are we meeting again?

**Comment by lernerb** [comment]
We will decide after class tomorrow. We all have a lot of work to do this week for other classes as well

**Comment by shuuri** [comment]
OK
