### ISSUE TITLE
Stuff to do now.

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#37]
5) Confidence for large images (set so hangar outputs correct)

**Comment by LTAcosta** [comment]
And move printing, correct?

**Comment by nsheaps** [comment]
Yep.

**Comment by LTAcosta** [comment]
I'll work on that while I wait for the over to preheat.

**Comment by LTAcosta** [comment]
I just pushed my changes to another branch. I haven't tested them yet though, so if somebody wants to do that, and then merge them in, that'd be great. I'm going to finish eating and should be down there in about 20 minutes.

**Comment by lernerb** [comment]
I just beat the shit out of that 1x1 matching code. Takes 30 seconds to run something that took many hours before #fuckyouclinger.

**Comment by LTAcosta** [comment]
Awesome

**Comment by lernerb** [comment]
andddddddddd i think i fixed our FFT's

**Comment by lernerb** [comment]
2:00am, lernerb had an idea to base the score size dependent on the source image size. It seems to be working. We shall run the code.

**Comment by lernerb** [comment]
2:21am, lernerb is quite pleased. Either from his lack of sleep or our programs progression throughout the last 13 hours. https://dl.dropboxusercontent.com/u/19806436/fuckyeahsoftwaredev.png

**Comment by lernerb** [comment]
2:28am, lernerb has pushed everything to develop. lernerb is doing one sanity test and then commiting the code to clinger so we have something at least

**Comment by lernerb** [comment]
2:34am, lernerb has completed his sanity tests. He has submitted our first working version of the code THAT TAKES CARE OF MULTIPLE MATCHES ALWAYS WOOO.

Your assignment has been submitted successfully.
Your confirmation number is b8a8ddf9

I added shit tons of comments to every function we have. Feel free to test develop, and try and break the inputs. Do not change logic or the cookie monster will come after you.

merp. merp. merp. done. with. software. dev. party.

**Comment by LTAcosta** [comment]
So I decided to go through and do a bit of code clean up and double check that we are outputting correctly. The 1x1s with big images is taking forever. Hopefully it does work though, I will report back when it finally prints something.

**Comment by lernerb** [comment]
It took 30 seconds for me. Do you have the latest ?

**Comment by lernerb** [comment]
turtles:SoftwareDev lernerb(develop)$ time ./spims -p /course/cs4500wc/Assignments/A7/Patterns/red1.png -sdir /course/cs4500wc/Assignments/A4/Sources

real    0m25.331s
user    0m43.587s
sys     0m1.128s

**Comment by lernerb** [comment]
turtles:SoftwareDev lernerb(develop)$ time ./spims -p /course/cs4500wc/Assignments/A7/Patterns/red1.png -sdir /course/cs4500wc/Assignments/A7/Sources/
red1.png matches greenish.png at 1x1+2+0
red1.png matches greenish.png at 1x1+3+1
red1.png matches greenish.png at 1x1+7+1
red1.png matches greenish.png at 1x1+4+2
red1.png matches greenish.png at 1x1+0+3
red1.png matches greenish.png at 1x1+5+3
red1.png matches greenish.png at 1x1+9+3
red1.png matches greenish.png at 1x1+1+4
red1.png matches greenish.png at 1x1+4+4
red1.png matches greenish.png at 1x1+6+4
red1.png matches greenish.png at 1x1+0+5
red1.png matches greenish.png at 1x1+3+5
red1.png matches greenish.png at 1x1+7+5
red1.png matches greenish.png at 1x1+2+6
red1.png matches greenish.png at 1x1+5+6
red1.png matches greenish.png at 1x1+8+7
red1.png matches greenish.png at 1x1+3+8
red1.png matches greenish.png at 1x1+6+8
red1.png matches greenish.png at 1x1+0+9

real    0m4.563s
user    0m5.660s
sys     0m0.224s

**Comment by LTAcosta** [comment]
i think the problem was a spacing issue after I did cleanup. Retrying now

**Comment by lernerb** [comment]
Also: Error: An exception occured while trying to find a match!

we absolutely do not want to print that. if we fail, fail silently on a thread.

**Comment by lernerb** [comment]
Can we meet in the lab for 15 minutes to discuss the rest?

**Comment by LTAcosta** [comment]
Sure. I have the worst luck with this fucking thing. I don't see how my code clean up messed things up :S

You there now?

**Comment by lernerb** [comment]
I'll be there in about 5 minutes. Nathan you wanna come and then we can go
to your place?

On Sun, Apr 14, 2013 at 4:54 PM, Lennon Acosta notifications@github.comwrote:

> Sure. I have the worst luck with this fucking thing. I don't see how my
> code clean up messed things up :S
> 
> You there now?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/37#issuecomment-16359291
> .

## 

Brandon Lerner

**Comment by nsheaps** [comment]
Yeah, I'll be down to the lab in a few minutes

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by shuuri** [comment]
Is there anything I can help with ?

**Comment by nsheaps** [comment]
Not really unless you want to keep me company

**Comment by shuuri** [comment]
Well then I guess I'll just resume writing my case studies. Let me know if
there's anything I can do to help.

**Comment by lernerb** [comment]
Closing as CCIS degree is done 😂

**Comment by LTAcosta** [comment]
It's about time. I've been waiting ages for an update!
