### ISSUE TITLE
Lets get stuff done.

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#4]
Everyone free this Thursday after 6pm?

**Comment by nsheaps** [comment]
eh

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
If no, what time?

On Mon, Feb 4, 2013 at 4:40 PM, Nathan Heaps notifications@github.comwrote:

> eh
> 
> Sincerely,
> 
> Nathan Heaps
> Dual CS/IS | Northeastern University | CCIS Class of 2014
> ResNet Computer Technician and System Administrator | (914) 907 - 7374
> 
> On Mon, Feb 4, 2013 at 4:23 PM, Brandon Lerner notifications@github.comwrote:
> 
> > Everyone free this Thursday after 6pm?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/4>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/4#issuecomment-13101136.

## 

Brandon Lerner

**Comment by nsheaps** [comment]
Never [?]

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by nsheaps** [comment]
Can we first decide what language we need to do and split up the work?
Rather than forcing us all to get together? Could we consider it more of a
chill and discuss session rather than a working session?

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
Yes we should all meet up and _decide_ on doing something. The first
meeting we should definitely do in person.

On Mon, Feb 4, 2013 at 5:06 PM, Nathan Heaps notifications@github.comwrote:

> Can we first decide what language we need to do and split up the work?
> Rather than forcing us all to get together? Could we consider it more of a
> chill and discuss session rather than a working session?
> 
> Sincerely,
> 
> Nathan Heaps
> Dual CS/IS | Northeastern University | CCIS Class of 2014
> ResNet Computer Technician and System Administrator | (914) 907 - 7374
> 
> On Mon, Feb 4, 2013 at 4:48 PM, Nathan Heaps nsheaps@gmail.com wrote:
> 
> > Never [?]
> > 
> > Sincerely,
> > 
> > Nathan Heaps
> > Dual CS/IS | Northeastern University | CCIS Class of 2014
> > ResNet Computer Technician and System Administrator | (914) 907 - 7374
> > 
> > On Mon, Feb 4, 2013 at 4:43 PM, Brandon Lerner notifications@github.comwrote:
> > 
> > > If no, what time?
> > > 
> > > On Mon, Feb 4, 2013 at 4:40 PM, Nathan Heaps notifications@github.comwrote:
> > > 
> > > > eh
> > > > 
> > > > Sincerely,
> > > > 
> > > > Nathan Heaps
> > > > Dual CS/IS | Northeastern University | CCIS Class of 2014
> > > > ResNet Computer Technician and System Administrator | (914) 907 -
> > > > 7374
> > > > 
> > > > On Mon, Feb 4, 2013 at 4:23 PM, Brandon Lerner <
> > > > notifications@github.com>wrote:
> > > > 
> > > > > Everyone free this Thursday after 6pm?
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/lernerb/SoftwareDev/issues/4>.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/lernerb/SoftwareDev/issues/4#issuecomment-13101136>.
> > > 
> > > ## 
> > > 
> > > Brandon Lerner
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/lernerb/SoftwareDev/issues/4#issuecomment-13101272>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/4#issuecomment-13102433.

## 

Brandon Lerner
