### ISSUE TITLE
Shit to do:

### ISSUE THREAD

**Issue by lernerb** [lernerb/SoftwareDev#7]
~~1) Make argument parsing valid (L)~~

~~2) Make sure inputs are images (L)~~

3) Figure out Numpy / Scipy to Make program faster (B,J)

~~4) Make source code readable (B,J)~~

~~5) Tester (N)~~

**Comment by nsheaps** [comment]
Did any work get accomplished today?

(Consider it a standup)

I got nothin

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
Can you run the tester to see which things are wrong while ya sleep?

**Comment by LTAcosta** [comment]
I finished 1 and 2, and did a little bit of 4. I made a pull request with my changes.

**Comment by shuuri** [comment]
Working on 3 for a while now and I'm kinda stumped cause I don't really what I'm doing. 

So far the best idea is to 
1. read the images through PIL 
2. convert to numpy Arrays                              <-- easy part 
3. do scipy fft to determine the correlation         <-- no idea still trying to figure it out 

http://pastebin.com/x1NJqWWm                    <--found an implementation for fft scipy but still trying to figure it out

**Comment by LTAcosta** [comment]
I also found this stackoverflow question. Not sure if it will help us, but maybe.

http://stackoverflow.com/questions/1819124/image-comparison-algorithm

**Comment by nsheaps** [comment]
haven't gotten around to the tester, hopefully will tonight.

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by LTAcosta** [comment]
Are we still meeting after this class?

**Comment by lernerb** [comment]
We can if we want to, or we can meet tomorrow because of the extension

**Comment by nsheaps** [comment]
I can be in the lab but I have some other work to focus on first.

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by LTAcosta** [comment]
If we choose to meet tomorrow, I will be free any time before software dev, but not after.

Also, when I was running the program via ssh, it was only taking 2 minutes, not 10. Not sure why it changed.

**Comment by nsheaps** [comment]
I won't be available tomorrow :-/

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by shuuri** [comment]
I can meet around 7:30 gotta meet with another group for a presentation tomorrow

**Comment by lernerb** [comment]
Probably the grayscale. Lets meet at 12p in the lab tomorrow if everyone's free.

**Comment by LTAcosta** [comment]
Why did we delete develop and make a new one? Our graph is less pretty now, lol

**Comment by lernerb** [comment]
Doesn't looks like it to me...

https://github.com/lernerb/SoftwareDev/commits/develop

whatever :P

On Fri, Feb 15, 2013 at 10:16 AM, Lennon Acosta notifications@github.comwrote:

> Why did we delete develop and make a new one? Our graph is less pretty
> now, lol
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/7#issuecomment-13610948.

## 

Brandon Lerner

**Comment by LTAcosta** [comment]
Oh, I think it was just that Nathan made changes to an old version of develop. Oh well, doesn't matter now.

**Comment by LTAcosta** [comment]
Oh, I see what you did, lol.

**Comment by LTAcosta** [comment]
Running a bit late. Should be there shortly.

**Comment by lernerb** [comment]
Same. Be there soon

**Comment by shuuri** [comment]
Are we meeting after class ?

**Comment by nsheaps** [comment]
I'm not, other obligations

Sincerely,

Nathan Heaps
Dual CS/IS | Northeastern University | CCIS Class of 2014
ResNet Computer Technician and System Administrator | (914) 907 - 7374

**Comment by lernerb** [comment]
We met earlier at like 12 and got a lot of stuff done, we can talk shortly
but I don't think we need to.

On Fri, Feb 15, 2013 at 2:42 PM, Nathan Heaps notifications@github.comwrote:

> I'm not, other obligations
> 
> Sincerely,
> 
> Nathan Heaps
> Dual CS/IS | Northeastern University | CCIS Class of 2014
> ResNet Computer Technician and System Administrator | (914) 907 - 7374
> 
> On Fri, Feb 15, 2013 at 2:37 PM, shuuri notifications@github.com wrote:
> 
> > Are we meeting after class ?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lernerb/SoftwareDev/issues/7#issuecomment-13624059>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lernerb/SoftwareDev/issues/7#issuecomment-13624268.

## 

Brandon Lerner

**Comment by shuuri** [comment]
Ok sounds good.

**Comment by lernerb** [comment]
Okay so he said that we don't care about speed for this assignment, and that it was one of the points of the prototype. Gonna close this issue, and we can do some research on numpy/scipy still.
